title: Joey Robinson
description: Ideas, experiments, and commentary on machine learning
theme: minima

lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

collections:
  posts:
    output: true

plugins:
- jekyll-seo-tag